var app = new Vue({
    el: "#app",
    data: {
        champions: [
            "Ash",
            "Atlas",
            "Barik",
            "Fernando",
            "Inara",
            "Khan",
            "Makoa",
            "Raum",
            "Ruckus",
            "Terminus",
            "Torvald",
            "Yagorath",
            "Bomb King",
            "Cassie",
            "Dredge",
            "Drogoz",
            "Imani",
            "Kinessa",
            "Lian",
            "Octavia",
            "Sha Lin",
            "Strix",
            "Tiberius",
            "Tyra",
            "Viktor",
            "Vivian",
            "Willo",
            "Furia",
            "Grohk",
            "Grover",
            "Jenos",
            "Mal'Damba",
            "Pip",
            "Seris",
            "Ying",
            "Io",
            "Corvus",
            "Androxus",
            "Buck",
            "Evie",
            "Koga",
            "Lex",
            "Maeve",
            "Moji",
            "Skye",
            "Talus",
            "Zhin",
            "Vatu",
            "Vora",
        ],
        users: ["Player 1", "Player 2", "Player 3", "Player 4"],
    },
});
